//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 02/04/2013 21:26:39
namespace WebService1
{
    
    /// <summary>
    /// There are no comments for empresaEntities in the schema.
    /// </summary>
    public partial class empresaEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new empresaEntities object using the connection string found in the 'empresaEntities' section of the application configuration file.
        /// </summary>
        public empresaEntities() : 
                base("name=empresaEntities", "empresaEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new empresaEntities object.
        /// </summary>
        public empresaEntities(string connectionString) : 
                base(connectionString, "empresaEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new empresaEntities object.
        /// </summary>
        public empresaEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "empresaEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for funcionario in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<funcionario> funcionario
        {
            get
            {
                if ((this._funcionario == null))
                {
                    this._funcionario = base.CreateQuery<funcionario>("[funcionario]");
                }
                return this._funcionario;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<funcionario> _funcionario;
        /// <summary>
        /// There are no comments for funcionario in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTofuncionario(funcionario funcionario)
        {
            base.AddObject("funcionario", funcionario);
        }
    }
    /// <summary>
    /// There are no comments for empresaModel.funcionario in the schema.
    /// </summary>
    /// <KeyProperties>
    /// codigo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="empresaModel", Name="funcionario")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class funcionario : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new funcionario object.
        /// </summary>
        /// <param name="codigo">Initial value of codigo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static funcionario Createfuncionario(int codigo)
        {
            funcionario funcionario = new funcionario();
            funcionario.codigo = codigo;
            return funcionario;
        }
        /// <summary>
        /// There are no comments for property codigo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int codigo
        {
            get
            {
                return this._codigo;
            }
            set
            {
                this.OncodigoChanging(value);
                this.ReportPropertyChanging("codigo");
                this._codigo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("codigo");
                this.OncodigoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _codigo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncodigoChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncodigoChanged();
        /// <summary>
        /// There are no comments for property nome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nome
        {
            get
            {
                return this._nome;
            }
            set
            {
                this.OnnomeChanging(value);
                this.ReportPropertyChanging("nome");
                this._nome = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("nome");
                this.OnnomeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nome;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnomeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnomeChanged();
        /// <summary>
        /// There are no comments for property matricula in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string matricula
        {
            get
            {
                return this._matricula;
            }
            set
            {
                this.OnmatriculaChanging(value);
                this.ReportPropertyChanging("matricula");
                this._matricula = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("matricula");
                this.OnmatriculaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _matricula;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmatriculaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmatriculaChanged();
    }
}
